segmentio/analytics.js-core

- component.json
- lib/analytics.js
- lib/cookie.js
- lib/group.js
- lib/memory.js
- lib/store.js
- lib/user.js
@ndhoule update dependency to use segmentio/bind-all to prevent wildcard dependency issue
> use segmentio/bind-all

- lib/pageDefaults.js
Reverts segmentio/analytics.js-core#22
Ref: https://segment.atlassian.net/browse/SEV-329
> Revert "update page defaults search method"

- lib/analytics.js
- test/analytics.test.js
https://segment.atlassian.net/browse/SCH-297
https://segment.atlassian.net/browse/SCH-298
@segmentio/schema
> [SCH-297][SCH-298] Add tracking plan support to identify and group traits

- test/analytics.test.js
- test/cookie.test.js
Reverts segmentio/analytics.js-core#67
This doesn't seem to have helped drastically.
> Revert "Fix flaky tests."

- .circleci/config.yml
This slipped through in the previous PR (https://github.com/segmentio/analytics.js-core/pull/77).
> Fix indentation level in Circle 2.0 config

- karma.conf.ci.js
- package.json
The progress reporter is quite hard to read on CI especially with multiple browsers.
This should be much easier to read.
> Use Karma Summary Reporter instead of progress reporter on CI

- lib/analytics.js
- package.json
- yarn.lock
Reverts segmentio/analytics.js-core#116
Going to take a different approach (and looks like from some testing that this might have broken page() calls)
> Revert "after fix"

- lib/cookie.js
- lib/user.js
- package.json
- test/cookie.test.js
- test/user.test.js
- yarn.lock
Ticket: https://segment.atlassian.net/browse/LIB-1583
CC: https://segment.atlassian.net/browse/CC-5997
---
> feat: use SameSite=Lax by default

- .circleci/changelog-check.sh
- .circleci/config.yml
- .github/CODEOWNERS
- HISTORY.md
- Makefile
- RELEASING.md
https://segment.atlassian.net/browse/LIB-1632
This PR updates HISTORY.md to include changes that weren't included in the history. It also adds libraries-team as a codeowner to the repo, and updates RELEASING.md to make sure we're properly updating the history when we do a release.
> (readme) Fix and improve release process

- lib/cookie.js
- lib/normalize.js
- package.json
- yarn.lock
Consolidating the changes from these PRs:
https://github.com/segmentio/analytics.js-core/pull/127
https://github.com/segmentio/analytics.js-core/pull/126
**Jira ticket**
https://segment.atlassian.net/browse/LIB-1595
**Tests**
Automated tests passing; released and tested on staging
> LIB-1591: Removed unnecessary packages

- HISTORY.md
- lib/analytics.js
- package.json
- test/analytics.test.js
- test/middleware.test.js
https://segment.atlassian.net/browse/LIB-1749
It is highly appreciated that you take the time to help improve Analytics.js.
We appreciate it if you would take the time to document your Pull Request.
Sadly, if we don't receive enough information, or the Pull Request doesn't
align well with our roadmap, we might respectfully thank you for your time, and close the issue.
Please ensure the following are completed to help get your PR merged:
Please respect our Code of Conduct, in short:
- Using welcoming and inclusive language.
- Being respectful of differing viewpoints and experiences.
- Gracefully accepting constructive criticism.
- Focusing on what is best for the community.
- Showing empathy towards other community members.
> rm checks to disallow adding middleware post-init

- HISTORY.md
- package.json
- test/normalize.test.js
This PR fixes a typo in a test changed by my previous PR
Test not required because this is a no-op change
> Fix typo on test

- test-e2e/ajs.codecept.js
- test-e2e/reference/anonymizing-ip-address.har
- test-e2e/reference/selective-destination-filtering.har
- test-e2e/reference/set-anonymous-id.har
- test-e2e/reference/traits-cached-and-cleared.har
This PR adds more test scenarios to e2e test
Testing not required
New version is not required because this PR is only adding tests
> Added test for set anonymous id

- package.json
- yarn.lock
This PR bumps a dev dependency version.
Testing
Testing completed successfully in local environment by running unit tests
Releasing
New version is not required because this PR is a dev change
> bumped analytics.js-integration version

- test-e2e/devServer.ts
- test-e2e/static/index.html
- test-e2e/static/index.js
This PR changes `devServer.ts` to set `Content-Security-Policy` headers and refactored the test website to move inline scripts from index.html to index.js.
Testing not required
New version is not required because this PR is only adding tests
> e2e test enables content security policy

- .circleci/config.yml
- .github/CODEOWNERS
- HISTORY.md
- Makefile
- lib/index.d.ts
This PR publishes a new version of ajs-core to publish the new typescript types definition
Testing completed successfully on previous PRs. No new testing necessary because this PR only publishes a new version.
> Publish types

- package.json
Bumps version o package.json
Testing not required because changes have been tested in other PRs
Adding the `New version is not required` string because HISTORY.md was updated in one of my latest PRs
> Publish v3.13.7

- package.json
This PR bumps the version to 4.1.0.  This release will include the changes in #194.  I forgot to bump the version in that PR.
Testing not required because  it is a no-op change.
New version is not required because #194 already specified a new version
> Bump Version to 4.1.0

- lib/analytics.ts
This PR fixes a wrong lib import.
No need to test such changes because they have already been tested in previous PRs. This change has been shipped to NPM on version 4.0.8 and its release train is already in progress
Testing not required because they have been tested on other pull requests and are being rolled out on a release train at the moment.
New version is not required because this is just a reset to older commits
> Fix url-component import

- .github/mergeable.yml
- HISTORY.md
- package.json
- yarn.lock
This PR updates `segmentio-facade` and removes `component-querystring` dependencies
Testing completed successfully on local via running ajs-core locally
These changes can be rolled out on a future release train (no need to coordinate a release train and release a new npm version just for this)
cc @pooyaj
> Update segmentio-facade and remove component-querystring

- README.md
> Link to Analytics Next
