segmentio/analytics.js-core

- component.json
Adds support for decoding `+`-encoded querystring spaces per w3 spec. closes https://github.com/segmentio/analytics.js/issues/470
https://github.com/component/querystring/pull/14
@ndhoule
> Bump component/querystring

- component.json
- lib/analytics.js
- test/analytics.js
This PR is to prompt a discussion regarding whether this is a feature we want to add and also regarding implementation.
I'm very open to doing this differently, but I think this is a solid approach / API. Since the existing implementation only allows triggering a **single** event and/or a **single** `identify` call (a querystring can only have one value for a given key), it seems appropriate to keep the existing params as the "triggers" and allow any additional parameters with a given prefix for traits (`ajs_trait_`) and properties (`ajs_prop_`) to "enrich" the calls triggered by `ajs_uid` and `ajs_event`, respectively. I'm happy to change the prefixes as well :)
We have *a lot* of customers who have asked for this. Most importantly, by restricting the functionality of the querystring API …
> Feature: Add support for populating traits and properties in querystring API

- circle.yml
Sauce Labs tests have been failing recently because they're all slow and racing to use Sauce Labs, and duo-test doesn't establish a singular Sauce tunnel. Serializing the tests will make them slower for the time being, but will improve reliability.
> Try serializing tests to fix Sauce issue

- lib/pageDefaults.js
This change makes it so that we grab the search parameter from the url directly instead of relying on `window.location.search`.
This was causing problems for users with SPAs with a # in their url structure as query parameters were included in `window.location.hash` instead of `window.location.search`.
@jgershen @sperand-io @ladanazita
> update page defaults search method

- HISTORY.md
- lib/analytics.js
- package.json
- test/analytics.test.js
PR changes the  handling of each integration's `.initialize` method to be run in a try/catch. This will ensure that if there are any bugs in the `.initialize` method of any given integration, it won't cause ajs to crash.
It also adds an array called `failedInitializations` to the prototype and stores the name of any failed integrations as a list. Next step will be to update the `analytics.js-segmentio-integration` to look for and pass this list back to our API in to be able to support replay.
> Add try catch to initialize

- HISTORY.md
- lib/analytics.js
- package.json
- test/analytics.test.js
PR updates previous PR with a couple of key changes:
1. It does the lookup for the `name` of a given integration from `integration.name` not `integration.prototype.name`. This is actually where this property will be located at runtime.
2. It removes the fallback to `Unknown` if the integration's name fails to resolve. It's actually not possible for an integration instance to initialize without a `name` property. Therefore, having a fallback adds unnecessary confusion to the code. Also, if this somehow does happen, falling back on `undefined` is not going to break this functionality.
3. It adds a check to the `_invoke` method of the `Analytics` class that ensures we do not try and run an integration method if that integration has failed to initialize properly. It also logs this.
> Add failed initializations lookup to invoke

- lib/analytics.js
- test/analytics.test.js
Ref: https://paper.dropbox.com/doc/Sending-Disabled-Events-evdrvByT2cYUErnrbAUa3
Previously, the tracking plan/schema was applied by our client side libraries and it would filter disabled events on the client (i.e. it would never be sent to api.segment.io).
Moving forwards, the client side libraries will switch to sending disabled events ONLY to the Segment integration (and hence api.segment.io). This will enable us to surface disabled events in the debugger.
> Send disabled events to Segment.

- karma.conf.ci.js
* Limit SauceLabs concurrency on CI.
* Increase RetryLimit on CI.
I'm seeing lots of intermittent failures on CI. I ssh'd into a running build and tweaking the concurrency and retryLimit  options seemed the most reliable way to ensure builds don't fail due to sporadic failures.
I picked 3 as the concurrency as any higher made the tests fail more often. I increased the retryLimit to 3 as I do see browsers failing to start quite often (at least once every build), and retrying more than twice for such a common failure seemed like a good idea. We could go higher, but I didn't have tests fail even once with retrying thrice.
Limiting concurrency will make CI builds slower. I think this is ok because this repo isn't that frequently updated, and I think this'll save us in the long run by not …
> Tweak Karma CI options

- karma.conf.ci.js
Looks like the previous updates still have some sporadic failures. This lowers the concurrency even more and increases the retry limit in an attempt to reduce flaky test failures.
> Tweak Karma CI config

- lib/analytics.js
- test/analytics.test.js
If an event is not present in the tracking plan, we'll now lookup the schema defaults for the project.
If the event is disabled in the schema default, it will only be sent to the Segment integration (i.e. api.segment.io).
If the event is enabled in the schema default, it will be sent to all integrations as indicated in .integrations.
Ref: https://paper.dropbox.com/doc/Schema-Client-Side-Defaults-DufdS8Ej43mnFXvvMqm1b
Existing test cases cover the behaviour for when the schema defaults are not rendered.
> Add support for schema defaults.

- HISTORY.md
- lib/analytics.js
- package.json
After the changes in
https://github.com/segmentio/analytics.js-private/pull/210
https://github.com/segmentio/snippet/pull/27
, the form that object representations of options can take will become much more dynamic due to their being directly passed in by the user. While testing, I found that objects containing circular references broke ndhoule clone as they caused a recursive overflow. Lodash's implementation handles this case and is generally better-maintained and tested so should replace the ndhoule version.
> replaced ndhoule clone with lodash clone

- HISTORY.md
- lib/analytics.js
- package.json
Lodash clone is a massive dependency. `extend` is much smaller and still results in correct deep cloning with circular references.
> Switch from lodash clone to cloning via extend

- test/analytics.test.js
- test/cookie.test.js
There are a few flaky tests here https://cloudup.com/cs68SLifvsj.
* Analytics #trackForm should call submit after a timeout
* cookie #set/#get should set a cookie
These seem to fail on IE mostly. Instead of suppressing these tests, we are going to be more lenient and retry these tests.
> Fix flaky tests.

- lib/analytics.js
- test/analytics.test.js
To be able to record client side metrics, we need to modify analytics.js-integration to start propagate errors to analytics.js-core (https://paper.dropbox.com/doc/Analytics.js-Metrics-SDD-1hAD90lqGS4aZxHAHYPu7#:h2=analytics.js-integration) so that analytics.js-core can record metrics.
Currently analytics.js-integration is responsible for guarding when an integration method throws an error. Before changing the behaviour in analytics.js-integration, we need to make sure analytics.js-core guards against errors in integrations.
> Catch and guard against Integration errors

- lib/analytics.js
- lib/metrics.js
- package.json
- test/analytics.test.js
- test/metrics.test.js
Ref: https://paper.dropbox.com/doc/Analytics.js-Metrics-SDD-1hAD90lqGS4aZxHAHYPu7
This makes two main changes:
* Add a metrics client for analytics.js to report metrics to
* Integrate metrics client into analytics.js to report key metrics
The metrics client buffers metrics in memory and periodically uploads them to a server. By default, the metrics client does not upload any metrics (though it points to api.segment.io). It also automatically flushes the buffer when an error metric is recorded. Lastly - the client supports sampling so we can control the metrics being reported.
Metrics are invoked for the following operations:
* A metric is recorded for each method invoked in analytics.js.
* A metric is recorded for each attempt to invoke an analytics.js integration.
* A metric is recorded …
> Add Metrics

- lib/metrics.js
- test/metrics.test.js
The client was incorrectly sending data as `metrics` instead of `series`. This was a bug in the SDD itself (fixed now).
> Fix Metrics Client Payload

- lib/metrics.js
- test/metrics.test.js
Discovered some more bugs during testing, two fixes here are:
1. type (i.e. Counter) is sent in titlecase, not lowercase.
2. Value must be sent. Since we only support incrementing by 1 on the client for now, this value is always 1.
> Fix metrics payload

- lib/analytics.js
- test/analytics.test.js
Adds an `integrations` option to `analytics.initialize()` that behaves exactly like the [page/identify/track/group/alias method's `integrations` option](https://segment.com/docs/sources/website/analytics.js/#selecting-destinations). It prevents any disabled device mode integrations from loading/initializing and automatically sets the `integrations` option on the page/identify/track/group/alias methods so that cloud mode integrations can be disabled too.
This is useful for disabling/enabling integrations at runtime based on user tracking consent (Do Not Track, GDPR, etc).
cc @segmentio/destinations-team @segmentio/cx-eng
> Add support for disabling integrations at runtime

- lib/analytics.js
- test/analytics.test.js
The tracking plan `All: false` is being stripped when `All: false` is passed in the load options, which makes the tracking plan mostly inert.
> Fix the tracking plan when load options are specified

- .circleci/config.yml
Seperate the commands for two reasons:
* see their output seperately
* time them seperately so we can better understand where the bottlenecks are (though 99.999% sure it's saucelabs :P)
> Split install into it's own step.

- test/cookie.test.js
this test flakes quite often. I haven't been able to reproduce at all locally even with saucelabs, so I'm adding logging to the test so that when it fails on CI, we have better visibility into what went wrong.
> add logging for cookie test

- test/cookie.test.js
A cookie test is randomly failing on Circle CI. It only happens on `Edge_17_17134_0_(Windows_10_0_0)`.
I can only reproduce it on SauceLabs (Circle CI or local), it works perfectly in a local VM with same versions and minimal configuration.
Failures on Circle CI : [#417](https://circleci.com/gh/segmentio/analytics.js-core/417), [#416](https://circleci.com/gh/segmentio/analytics.js-core/416), [#415](https://circleci.com/gh/segmentio/analytics.js-core/415)
> cookie #set should set a cookie - Edge_17_17134_0_(Windows_10_0_0).@segment/analytics.js-core.cookie
> ```js
> AssertionError: null deepEqual { a: 'b' }
> ```
---
Resetting `document.cookie` using `beforeEach` instead of `before` seems to fix the issue.
I ran 15+ successful test iterations after this PR, while I was getting ~1 failure …
> Clear cookies before each cookie test

- karma.conf.ci.js
The summary reporter doesn't show any details about test failures.
This adds back the  spec reporter but configures it to suppress output about failed tests.
> Improve CI reporting

- .circleci/config.yml
The previous configuration would run the publish step if the tag matched a version tag, OR if the branch was `master`.
ideally we would run this only if there was a version tag AND the branch was `master`, but this should work for now.
> Publish only on version tags

- .circleci/config.yml
- .gitignore
- karma.conf.ci.js
* store junit results in junit-reports (and ignore this in VCS)
* upload `junit-reports`
Tested with https://cloudup.com/cYI1-JJiZWh (https://circleci.com/gh/segmentio/analytics.js-core/517)
> Report pretty test summary in CI

- .circleci/config.yml
- .eslintrc
- .prettierrc
- Makefile
- lib/analytics.js
- lib/cookie.js
- lib/entity.js
- lib/group.js
- lib/metrics.js
- lib/normalize.js
- lib/store.js
- lib/user.js
- package.json
- test/.eslintrc
- test/analytics.test.js
- test/index.test.js
- test/metrics.test.js
- test/normalize.test.js
- test/tests.test.js
- test/user.test.js
- yarn.lock
This PR adds `prettier-eslint`, which is just `prettier` with its output piped to `eslint --fix`. `js` files are formatted using `eslint` rules, while `md` and `json` files only using `prettier`.
`husky` is added to setup a Git `precommit` hook, and `lint-staged` to only check staged files. This will make sure every commit is properly formatted and passes the lint test. This can be bypassed by using the Git `commit` `--no-verify` option.
A `format` script is added to run `prettier` on all files.
---
https://segment.atlassian.net/browse/LIB-413
cc @f2prateek
> Add prettier + eslint

- karma.conf.js
- test/cookie.test.js
- Increase the Mocha and Karma timeout to fix timeout errors
- Fix the cookie tests by using a random key instead, in case other tests are running
On a total of 28 tests : 
- 19 successful tests
- 1 failure ([#59](https://circleci.com/gh/fathyb/analytics.js-core/59)) due to the remove cookie test failing
- fixed it by using a random key for all tests
- 6 failures ([#66](https://circleci.com/gh/fathyb/analytics.js-core/66), [#57](https://circleci.com/gh/fathyb/analytics.js-core/57), [48](https://circleci.com/gh/fathyb/analytics.js-core/48), [#47](https://circleci.com/gh/fathyb/analytics.js-core/47), [#46](https://circleci.com/gh/fathyb/analytics.js-core/46), [44](https://circleci.com/gh/fathyb/analytics.js-core/44)) due to SauceLabs being down
- 2 failures due to unrelated tests :
- …
> Fix flaky test - Attempt 2

- .circleci/config.yml
was accidentally called "deploy"
> fix publish step in circle config

- README.md
- RELEASING.md
- package.json
- yarn.lock
np is nice for a few things:
* stricter checks (e.g. can't publish from a branch without forcing)
* human readable version bumps (e.g. minor, major, patch)
* supports distribution tags
* public (doesn't require our private robofiles)
* more user friendly UI
The one disadvantage is that it publishes directly to NPM locally, so we'll need to use the `--no-publish` flag to avoid releasing from our local dev machines and have the CI do it instead (following https://github.com/sindresorhus/np#publish-with-a-ci). I added a helper script that has this flag set by default to make it easy to run as well.
> Replace robo with np for releasing.

- lib/entity.js
- test/group.test.js
- test/user.test.js
This changes entity.js to dual  write ids to localStorage and the cookies.
Reads will check the cookie first, and fallback to the localStorage when a cookie is not available. When cookies are not available during reads, and localStorage is, we write the value to the cookie as well.
> LIB-868: Update entity.js to support localStorage

- lib/normalize.js
- package.json
- test/normalize.test.js
- yarn.lock
Currently message Ids are generated in the [Segmentio integration](https://github.com/segment-integrations/analytics.js-integration-segmentio/blob/master/lib/index.js#L316) for analytics.js. This moves the id generation logic further upstream so that client-side integrations can use the messageId. 
This will be deployed by releasing a commit of analytics.js-private that simultaneously pulls in:
- a version of a.js-core with the logic in this PR
- a version of the segmentio integration with the messageId generation logic removed.
> Generate MessageId

- lib/entity.js
- lib/user.js
- test/group.test.js
- test/user.test.js
This updates entity.js and user.js to dual write ids to localStorage and the cookies. This applies
to userId, groupId and anonymousIds. Reads will check the cookie first, and fallback to the
localStorage when a cookie is not available. When cookies are not available during reads, and
localStorage is, we write the value to the cookie as well.
> feat(ids): check LocalStorage when cookies are not available

- lib/entity.js
- lib/user.js
- test/group.test.js
- test/user.test.js
This adds a flag `localStorageFallbackDisabled` to disable the localStorage fallback code.
`localStorageFallbackDisabled` is falsy by default, hence the fallback code is opt in by default, and requires opt out.
Since the configuration for users and groups are supplied seperately, to use this you need to pass in:
```
analytics.initialize(settings, {
user: {
localStorageFallbackDisabled: true,
},
group: {
localStorageFallbackDisabled: true
}
})
```
> feat(ids): add `localStorageFallbackDisabled` flag

- lib/analytics.js
- lib/middleware.js
- package.json
- test/analytics.test.js
- test/middleware.test.js
- yarn.lock
This PR moves to add integration-level middleware support to analytics.js. It does so by exposing a new property called `_integrationMiddlewares`. To easily allow users and applications to interface with this long-term, we expose an `addIntegrationMiddleware` method that'll be the entrypoint going forward.
Middlwares are expected to accept two arguments - an object payload and a function callback. A final "middleware" callback is appended to continue the normal ajs call pipeline once all middlewares - if any - have been applied.
CC @f2prateek for first review so we can clean up anything desired and get this out the door! :)
> Add middleware support

- lib/analytics.js
- lib/middleware.js
- test/analytics.test.js
- test/middleware.test.js
Adds source middleware support according to [SDD: A.js Middleware](https://paper.dropbox.com/doc/SDD-A.js-Middleware--AoE9hHeT7t9Dl~eB9KeSpymBAg-ncVpU4C2wxHKjYnHQxcmk).
This does not break the integration middleware support, the API and behavior should be the same.
**Examples**:
- filter by integration
```js
analytics.addSourceMiddleware(({payload, next, integrations}) => {
if (payload.type === 'identify' && 'Appboy' in integrations) {
const storedTraits = analytics.user().traits()
const newTraits = payload.traits()
// Only send the event to Braze if a trait has changed
integrations.Appboy = diff(storedTraits, newTraits)
}
next(payload)
})
```
- filter an event
```js
analytics.addSourceMiddleware(({payload, next}) => {
if (shouldSend) {
next(payload)
}
else {
next(null)
}
})
```
- enrich …
> feat(middleware): add source middleware support

- lib/analytics.js
- package.json
- test/analytics.test.js
For https://segment.atlassian.net/browse/LIB-1430
This PR removes the dependency on "after" which violated customer CSP with a new Function() call.
> remove after dependency

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This is a first pass at modernizing/updating this repo! This will be a WIP over the coming sprints.
Todo -
> [readme] Modernize a.js-core repo

- HISTORY.md
- package.json
- yarn.lock
This PR strips out all of the unnecessary info from package.json which gets exposed by browserify when we include it to pull the analytics.js-core version number.
This has been tested in staging - 
Before, it would have looked something like this:
After:
This is in reference to https://github.com/segmentio/analytics.js-core/issues/37 (LIB-146)
> Only include version in package.json browserify

- HISTORY.md
I accidentally tagged the last version as `minor` instead of `patch`. This PR fixes the history to comply with what's deployed.
Testing not required because it's a no-op.
> docs: fix history

- lib/analytics.js
- lib/middleware.js
- test/analytics.test.js
https://segment.atlassian.net/browse/LIBWEB-168
This pull request adds destination middleware to AJS and deprecates integration middleware. Destination middleware is similar to integration middleware, the key difference being in the interface for how it is added to AJS:
Destination Middleware:
addDestinationMiddleware(integrationName, middlewares)
Integration Middleware:
addIntegrationMiddleware(middleware)
Destination middleware only applies to the specific integration specified in the call to addDestinationMiddleware whereas integration middleware applies to all enabled integrations. The middlewares argument is an array which can contain one or many middlewares to add for this destination.
This is an example of adding a destination middleware that sets the username to 'foo' for the …
> Add destination mw

- HISTORY.md
- lib/cookie.js
- package.json
- test/cookie.test.js
Ticket: https://segment.atlassian.net/browse/LIBWEB-90
> fix(cookies): null values should delete cookies

- HISTORY.md
- lib/analytics.js
- lib/middleware.js
- package.json
- test/analytics.test.js
This PR adds destination middleware support. This feature was originally released to master but was then reverted as a regression was discovered. That regression was addressed by this commit ( https://github.com/segmentio/analytics.js-core/pull/150/commits/010219b675e859d35deafaf8c1e387461839c694 ) and we are re-releasing.
Run this code in the console of a project connected to a mixpanel destination and then observe the identify event in mixpanel with user id foobarcat
```
f=function({payload, next, integrations}) {payload.obj.userId = "foo"; next(payload);}; analytics.addSourceMiddleware(f);
f=function(payload, integration, next) {payload.obj.userId = payload.obj.userId + "bar";next(payload);}; analytics.addIntegrationMiddleware(f);
f=function({payload, integration, next}) { …
```
> Add dest mw take two

- test-e2e/ajs.codecept.js
- test-e2e/reference/cookies-and-local-storage.har
- test-e2e/reference/login-as-different-user.har
- test-e2e/static/index.html
This PR updated the tests to cover page / identify / track / alias / group calls, as well as adding another test scenario. 
Testing completed successfully by running `make test-e2e` and see that tests passed.
```
$ make test-e2e
yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.42s.
(pkill SIGTERM ajs-test-e2e-dev-server) || true
yarn ts-node ./test-e2e/devServer.ts &
rm -rf ./test-e2e/output
rm -rf ./test-e2e/staging
mkdir ./test-e2e/staging
yarn wait-on http://localhost:8000 && npx codeceptjs run --steps
yarn run v1.22.4
yarn run v1.22.4
$ /Users/kinglong.tse/dev/src/github.com/segmentio/analytics.js-core/node_modules/.bin/ts-node ./test-e2e/devServer.ts
$ /Users/kinglong.tse/dev/src/github.com/segmentio/analytics.js-core/node_modules/.bin/ …
```
> test now covers p/i/t/a/g

- lib/cookie.ts
This PR moves `cookies.js` to `cookies.ts` and add types to its functions.
Testing completed successfully using `make watch-e2e` in ajs private
Release not necessary because this is a dev only change
> Move cookies.js to cookies.ts and add types

- lib/entity.ts
This PR moves `entity.js` to `entity.ts` and adds types to its functions
- Testing completed successfully using `make test-e2e` and `make watch` from ajs private
Release not necessary because it's a dev-only change
> [LIBWEB-260] [TS] Move entity.js to entity.ts

- .github/PULL_REQUEST_TEMPLATE.md
- lib/group.ts
- lib/memory.ts
- lib/metrics.ts
- lib/normalize.ts
- lib/pageDefaults.ts
- lib/store.ts
- lib/types.ts
This PR converts `group`, `memory`, `metrics`, `normalize`, `pageDefaults` and `store` to `.ts`.
Testing completed successfully using `make test-e2e` and `make watch` from ajs private:
New version is not required because this is a dev only change
> Convert group, memory, metrics, normalize, pageDefaults and store to .ts

- lib/analytics.ts
- lib/cookie.ts
- lib/entity.ts
- lib/metrics.ts
- lib/store.ts
- lib/user.ts
Noticed some APIs have get and set functionality bu the typescript types didnt reflect this.
Soooo happy to see updated being made to this repo and especially the adoption of typescript!! Thank you so much!
- Testing completed successfully by @juliofarah using internal tools and e2e tests:
-->
New version is not required because this is a dev-only change
> Added optional to args that get and set

- README.md
This PR updates AJS Core README to include documentation on how to use types when using the AJS Snippet
Testing not required because this is only a documentation change.
New version is not required because this is only a documentation change.
> Document how to use types with the AJS snippet

- README.md
Updated the docs to explain how to use the open source npm package. 
- Testing completed successfully using code-sandbox build https://codesandbox.io/s/awesome-butterfly-2qfoz?file=/src/index.js
- Testing not required because it is only the docs
New version is not required because it is just a readme change
> readme: adding instructions to use the npm module

- package.json
- yarn.lock
This PR adds a commit hook that blocks adding new JS files.
- Testing not required because this is a dev-only change
New version is not required because it's a dev-only change
> Add commit hook to prevent JS from being added

- HISTORY.md
- lib/analytics.ts
- package.json
This PR removes the library `@ndhoule/foldr` in favor of the function `Array.prototype.reduce`
Testing completed successfully by verifying existing unit tests pass
> Replace @ndhoule/foldl with Array.prototype.reduce

- package.json
- yarn.lock
This PR addresses some dependencies with critical vulnerabilities.  The packages in question are:
- `growl`
- `handlebars`
`growl` is a dependency of `mocha`, so we are just bumping to the latest version prior to dropping IE9 support (which is V5 and, unfortunately, cannot drop).  This version of mocha has a version of growl that addressed this issue.
`handlebars` is a dependency of `instabul`, which has not been updated in about 3 years.  `istanbul` also does not appear to be a dependency we actually need (we use https://github.com/istanbuljs/istanbuljs for karma coverage).  Therefore, we can drop this package.
Testing completed successfully using unit tests.
New version is not required because it's a dev-only change.
> Address some critical vulnerabilities

- package.json
- yarn.lock
This PR addresses some dependencies with high vulnerabilities.  The packages in question are:
- `lodash`
- `watchify`
Both of these deps can be manually updated.  We also need to enforce the version of `browserify` via the resolutions config option so we always use the latest version of `elliptic`.  The latest version of watchify, unfortunately, is using an outdated version of browersify.
Testing completed successfully using unit tests.
New version is not required because it's a dev-only change.
> Fix high vulnerabilities (again) and enforce browserify version

- package.json
- yarn.lock
This PR enforces the version of lodash.  We missed this in #200 
Testing completed successfully using unit tests.
New version is not required because it's a dev-only change.
> Enforce lodash version

- HISTORY.md
- package.json
- yarn.lock
This PR addresses some dependencies with low vulnerabilities.  The packages in question are:
- `jquery`
- `node-fetch`
- `debug`
These deps were either manually updated or enforced to a safe version via the `resolutions` config
Testing completed successfully using unit tests.
> Bump deps with low vulns

- HISTORY.md
- lib/analytics.ts
- lib/index.d.ts
- package.json
This changes the args of the main methods to be optional to match the documentation:
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#basic-tracking-methods
Testing completed successfully by checking that the generated typedef has correct types for the method args.
> Change the args of the main methods to be optional

- HISTORY.md
- package.json
- tsconfig.json
This PR turns on the `esModuleInterop` tsconfig setting.  This setting currently defaults to `false` and is causing issues in versions newer than 4.0.4.
Fixes #205 
See more details https://github.com/lodash/lodash/issues/3192#issuecomment-411963038
Testing completed successfully using e2e tests and sandbox with 4.1.1-beta1 version
> Turn on esModuleInterop

- HISTORY.md
- lib/entity.ts
- package.json
- test/analytics.test.ts
- yarn.lock
This PR replaces `@ndhoule/extend` with `lodash.assignin`. 
- Testing completed successfully using e2e tests and unit tests
> Replace @ndhoule/extend with lodash.assignin

- HISTORY.md
- lib/analytics.ts
- package.json
- yarn.lock
This PR replaces the function `pick`, provided by `@ndhoule/pick`, with the version provided by `lodash.pick`
Testing completed successfully using unit tests and e2e tests.  Note how my prop `search` overrides the `page.context` value.
> Replace @ndhoule/pick with lodash.pick

- HISTORY.md
- lib/normalize.ts
- lib/pageDefaults.ts
- package.json
- yarn.lock
This PR replaces `includes`, provided by `@ndhoule/includes`, with the one provided by `lodash.includes`.  Unfortunately, we cannot leverage `String.prototype.includes` because it is not available in any version of IE.
Testing completed successfully using e2e tests and unit tests.  See examples below:
- Triggering a `page` call on a HTML document with a  `<link rel="canonical" href="http://taco:3000" />`
- Triggering a `page` call on a HTML document with a  `<link rel="canonical" href="http://taco:3000?cheese=false" />`
- Triggering `page` with no `canonical` url
> Replace @ndhoule/includes with lodash.includes

- HISTORY.md
- lib/analytics.ts
- lib/cookie.ts
- lib/entity.ts
- lib/normalize.ts
- lib/store.ts
- lib/types.ts
- package.json
- test/analytics.test.ts
- test/cookie.test.ts
- test/normalize.test.ts
- test/store.test.ts
- yarn.lock
This PR rips out the third party library `@ndhoule/defaults` and replaces it with merges via the ES6's object spread syntax.
Testing completed successfully using verifying existing unit tests pass and adding additional test coverage.  Also verified with e2e tests using the scenarios below:
Each scenario shows me overriding `context.page.search` with `lol`
*Note*: There is an existing bug where the `properties` doesn't reflect changes to `context.page`.  This does not happen in other methods
> Replace @ndhoule/defaults with ES6 spread syntax merging

- HISTORY.md
- karma.conf.ts
- lib/analytics.ts
- lib/pageDefaults.ts
- package.json
- test/analytics.test.ts
- test/pageDefaults.test.ts
- tsconfig.json
- yarn.lock
This PR removes the `@segment/canonical` library in favor of `document.querySelector`.  We also are upgrading some test libraries like `sinon`.
Note: We can't use the latest version of sinon because sinon 2+ only supports IE11+
Testing completed successfully using unit tests and writing new tests
> Drop @segment/canonical.  Also uprade some libs

- karma.conf.coverage.ts
- karma.conf.ts
- lib/middleware.ts
- package.json
- test/analytics.test.ts
- test/middleware.test.ts
- test/pageDefaults.test.ts
- yarn.lock
This PR fixes code coverage metrics.  I broke this when I merged #196.  Since `karma-typescript` handles all the work for us, we can actually remove `karma-coverage` and it's configuration.
Testing not required because it is a dev only change.
New version is not required because it's a dev-only change
> Fix code coverage

- HISTORY.md
- package.json
- yarn.lock
This PR patches the ReDoS vulnerability with the `trim` package. This package was used in the following dependencies: 
- `component-querystring` 
- `facade` ( the version used by AJS classic ) 
I have to go to the yarn resolution route, as the `component-querystring` hasn't published the updated package. 
Testing completed successfully using local unit tests;
Testing completed successfully using local e2e build of the final bundle;
> pin trim version

- README.md
No-op, just fixing a typo on Readme.MD
Testing not required
> [No-op] Fix typo on Readme

- package.json
- yarn.lock
This PR updates the following dependencies:
- elliptic
- ini
- socket.io
- debug
- Testing completed successfully using npm package built locally.
No regression added:
- Publish version 4.1.9 to npm
- Schedule a release train
> Upgrade dependencies to fix security vulns

- HISTORY.md
- package.json
- yarn.lock
This PR upgrades `top-domain` to 3.0.1 to upgrade nested dependencies such as `component-cookies`, `debug` and `ms` that had security vulnerabilities.
- Testing completed successfully locally using analytics.js-core v 4.1.10-beta.0, published to NPM and a local react app.
- Once the beta version is tested, update package.json to remove the beta tag and run `npm publish`;
> Upgrade top-domain to 3.0.1

- package.json
All this PR does is bump the version of ajs core to 4.1.11 - no changes to logic.
The actual change (removing the console.log) is on local `build/` files generated by `make build`.
- Testing not required because this is a no-op
New version is not required because this is a no-op
> [Noop] Remove console.log from built files
